import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import CodeEditor from '../components/CodeEditor'

const Home: NextPage = () => {
  const [code, setCode] = useState('')
  const [currLanguage, setCurrLanguage] = useState('javascript')
  const [output, setOutput] = useState('')

  const handleCodeChange = (code: string, language: string) => {
    setCode(code)
    setCurrLanguage(language)
  }

  const handleCodeSubmit = () => {
    console.log(code, currLanguage)
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CodeEditor
        onCodeChange={handleCodeChange}
      />
      <button onClick={handleCodeSubmit}>Submit</button>
    </div>
  )
}

export default Home
