import type { NextPage } from 'next';
import { useState } from 'react';
import Head from 'next/head';
import MenuBar from '../components/MenuBar/notebookOptionsBar';
import NavBar from '../components/NavBar';
import SideBar from '../components/SideBar';
import Panel from "../components/Panel";
import { useSelector } from "react-redux";
import { AppState } from '../lib/typings/types';
import lightTheme from '../styles/themes/lightTheme';
import darkTheme from '../styles/themes/darkTheme';
import { ThemeProvider, CssBaseline } from '@mui/material';
import Notebook from '../components/Notebook';
import NotebookTabPanel from '../components/NotebookTabPanel';

const Home: NextPage = () => {
  const { config } = useSelector((state: { app: AppState }) => state.app)
  const [showPanel, setShowPanel] = useState<string | null>(null)

  return (
    <ThemeProvider theme={config.notebookThemeMode == "light" ? lightTheme : darkTheme}>
      <CssBaseline />
      <div>
        <Head>
          <title>Dnotebook - Exciting Notebook experience</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className='flex-row'>
          <section>
            <NavBar />
          </section>
          <section>
            <MenuBar />
          </section>
          <section
            className="overflow-hidden h-full mt-2"
            style={{
              display: "flex",
              height: "90vh",
            }}
          >
            <div className="sticky flex-none h-full border-r-2">
              <SideBar setShowPanel={setShowPanel} showPanel={showPanel} />
            </div>
            {showPanel && (
              <div className="sticky flex-none h-full border-r-2 w-72">
                <Panel showPanel={showPanel} />
              </div>
            )}
            <div
              className="col-span-12 min-h-1/2 px-3.5 overflow-y-scroll"
              style={{
                width: "100%",
              }}
            >
              <NotebookTabPanel />
              <Notebook />
            </div>
          </section>
        </div>
      </div>
    </ThemeProvider>
  )
}

export default Home
